from ex1.factories import HealingCreatureFactory, TransformCreatureFactory

if __name__ == "__main__":
    print("Testing Creature with healing capability")
    print("base:")
    heal_factory = HealingCreatureFactory()
    base_healer = heal_factory.create_base()
    print(base_healer.describe())
    print(base_healer.attack())
    print(base_healer.heal())
    print("\nevolved:")
    evolved_healer = heal_factory.create_evolved()
    print(evolved_healer.describe())
    print(evolved_healer.attack())
    print(evolved_healer.heal())
    print("\nTesting Creature with transform capability")
    print("base:")
    transform_factory = TransformCreatureFactory()
    base_transformer = transform_factory.create_base()
    print(base_transformer.describe())
    print(base_transformer.attack())
    print(base_transformer.transform())
    print(base_transformer.attack())
    print(base_transformer.revert())
    print("\nevolved:")
    evolved_transformer = transform_factory.create_evolved()
    print(evolved_transformer.describe())
    print(evolved_transformer.attack())
    print(evolved_transformer.transform())
    print(evolved_transformer.attack())
    print(evolved_transformer.revert())
